# Configuration for the NixOS host. Includes nixarchy (Omarchy) and
# replaces the GNOME/GDM desktop with Omarchy's Hyprland behind SDDM.
{ config, lib, pkgs, nixarchy, ... }:

let
  # Launch a browser with Mesa EGL (the GPU Hyprland composites on) and the
  # matching VAAPI driver, working around cross-GPU DMA-BUF import failures on
  # hybrid NVIDIA + iGPU laptops (EGL_BAD_MATCH, black screens, flicker).
  # Applied from ~/Downloads/fix_chromium.md. Desktop overrides in
  # ~/.local/share/applications/ route the launcher entries through these.
  browserLauncher = launcher: binary: pkgs.writeShellScriptBin launcher ''
    MESA_EGL=/run/opengl-driver/share/glvnd/egl_vendor.d/50_mesa.json
    if [[ -f $MESA_EGL ]]; then
      export __EGL_VENDOR_LIBRARY_FILENAMES="$MESA_EGL"
    fi

    IGPU="$(lspci 2>/dev/null | grep -iE 'vga|3d|display' | grep -iv 'nvidia' | grep -iE 'intel|amd|advanced micro devices|radeon|ati ')"
    if echo "$IGPU" | grep -qi intel; then
      export LIBVA_DRIVER_NAME=iHD
    elif [[ -n $IGPU ]]; then
      export LIBVA_DRIVER_NAME=radeonsi
    fi

    exec ${binary} \
      --ozone-platform=wayland \
      --ozone-platform-hint=wayland \
      --password-store=gnome-libsecret \
      --enable-features=TouchpadOverscrollHistoryNavigation \
      "$@"
  '';
in
{
  imports =
    [
      # Include the results of the hardware scan.
      ./hardware-configuration.nix
      # App/service selection generated by nixarchy-apply from
      # ~/.config/nixarchy/{apps,services,advanced}.nix
      ./nixarchy-apps.nix
      nixarchy.nixosModules.nixarchy
    ];

  ##########################################################################
  # Omarchy (nixarchy)
  ##########################################################################
  programs.nixarchy = {
    enable = true;
    user = "mihai";
  };

  # The doctor reported gdm is currently greeting. The user chose to replace
  # it with nixarchy's SDDM, so displayManager stays at its default (true)
  # and GDM/GNOME below are disabled -- two display managers at once refuses
  # to build.

  ##########################################################################
  # Bootloader.
  ##########################################################################
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos";
  networking.networkmanager = {
    enable = true;
    # Periodic connectivity probe so NetworkManager can detect captive portals.
    settings.connectivity = {
      uri = "http://nmcheck.gnome.org/check_network_status.txt";
      interval = 60;
      response-timeout = 10;
    };
  };

  # Hyprland has no built-in captive portal popup, so open the login page from
  # a NetworkManager dispatcher hook when connectivity becomes "portal".
  environment.etc."NetworkManager/dispatcher.d/50-captive-portal.sh" = {
    mode = "0755";
    text = ''
      #!/bin/sh
      [ "$2" = "connectivity-change" ] || exit 0
      case "$CONNECTIVITY_STATE" in
        portal)
          notify-send -i network-wireless "Captive portal" "Opening login page..."
          runuser -u mihai -- xdg-open http://nmcheck.gnome.org/ &
          ;;
      esac
    '';
  };

  # Set your time zone.
  time.timeZone = "Europe/Bucharest";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "ro_RO.UTF-8";
    LC_IDENTIFICATION = "ro_RO.UTF-8";
    LC_MEASUREMENT = "ro_RO.UTF-8";
    LC_MONETARY = "ro_RO.UTF-8";
    LC_NAME = "ro_RO.UTF-8";
    LC_NUMERIC = "ro_RO.UTF-8";
    LC_PAPER = "ro_RO.UTF-8";
    LC_TELEPHONE = "ro_RO.UTF-8";
    LC_TIME = "ro_RO.UTF-8";
  };

  # Omarchy provides its own Wayland session via SDDM. GDM and the GNOME
  # desktop are removed -- nixarchy's SDDM greeter replaces them.
  services.desktopManager.gnome.enable = lib.mkForce false;
  services.displayManager.gdm.enable = lib.mkForce false;

  # Configure keymap.
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  ##########################################################################
  # Graphics -- Intel + NVIDIA hybrid, sync mode (doctor recommendation).
  ##########################################################################
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver
      nvidia-vaapi-driver
    ];
  };

  environment.variables = {
    LIBVA_DRIVERS_PATH = "/run/opengl-driver/lib/dri";
    OMARCHY_SCREENRECORD_USE_PORTAL = "true";
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  hardware.nvidia.prime = {
    sync.enable = true;
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
  };

  ##########################################################################
  # Kernel -- latest stable.
  ##########################################################################
  boot.kernelPackages = pkgs.linuxPackages_latest;

  ##########################################################################
  # Memory -- zram compressed swap.
  ##########################################################################
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # Define a user account.
  users.users."mihai" = {
    isNormalUser = true;
    description = "Mihai";
    extraGroups = [ "networkmanager" "wheel" "input" "libvirtd" ];
    packages = with pkgs; [
      git
      wget
      curl
      opencode
      google-chrome
    ];
  };

  # GNOME Boxes needs the libvirt/QEMU stack to check and use KVM. Without it
  # Boxes fails its virsh check and reports "Oops! no KVM" even though /dev/kvm
  # and the kvm-intel module are fine.
  virtualisation.libvirtd.enable = true;

  # Install firefox.
  programs.firefox.enable = true;

  # Passwordless sudo for the wheel group
  security.sudo.wheelNeedsPassword = false;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile.
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    vim
    (browserLauncher "omarchy-launch-chromium" "${pkgs.chromium}/bin/chromium")
    (browserLauncher "omarchy-launch-google-chrome" "${pkgs.google-chrome}/bin/google-chrome-stable")
  ];

  system.stateVersion = "26.05";
}
